apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-deploym
spec:
  selector:
    matchLabels:
      app: iris-app
  replicas: 3
  template:
    metadata:
      labels:
        app: iris-app
        type: microservice
    spec:
      containers:
      - name: iris-app
        image: alfrizz/iris_image:latest
        ports:
        - containerPort: 7000
          protocol: TCP

 

