apiVersion: v1
kind: Service
metadata:
  name: iris-service
  labels:
    app: iris-app
spec:
  selector:
    app: iris-app
    type: microservice
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 7000
    nodePort: 32000
  type: LoadBalancer
